In [1]:
import numpy as np
import gamspy as gams
import pandas as pd
import sys

# For detailed instructions from GAMS, see:
# https://gamspy.readthedocs.io/en/latest/user/notebooks/trnsport.html


def print_records(vars):
    for k in np.arange(0, len(vars)):
        print(vars[k].name, ':')
        display(vars[k].records)
        print()


m = gams.Container()

i = gams.Set(container=m,
             name='i',
             description='Plant')

j = gams.Set(container=m,
             name='j',
             description='Market')

i.setRecords(['Seattle', 'San Diego'])
j.setRecords(['New York', 'Chicago', 'Topeka'])

print_records([i, j])

a = gams.Parameter(container=m,
                   name='a',
                   domain=i,
                   description='Supply of commodity at plant i')

b = gams.Parameter(container=m,
                   name='b',
                   domain=j,
                   description='Demand for commodity at market j')

a.setRecords([('Seattle', 350), ('San Diego', 600)])
b.setRecords([('New York', 325), ('Chicago', 300), ('Topeka', 275)])

print_records([a, b])

distances = pd.DataFrame(
    [
        ['Seattle', 'New York', 2.5],
        ['Seattle', 'Chicago', 1.7],
        ['Seattle', 'Topeka', 1.8],
        ['San Diego', 'New York', 2.5],
        ['San Diego', 'Chicago', 1.8],
        ['San Diego', 'Topeka', 1.4],
    ],
    columns=['From', 'To', 'Distance']
).set_index(['From', 'To'])

d = gams.Parameter(container=m,
                   name='d',
                   domain=[i, j],
                   description='Distance between plant i and market j',
                   records=distances.reset_index(),)

c = gams.Parameter(container=m,
                   name='c',
                   domain=[i, j],
                   description='Cost per unit of shipment between' +
                   'plant i and market j')

x = gams.Variable(container=m,
                  name='x',
                  domain=[i, j],
                  type='Positive',
                  description='Amount of commodity to ship from' +
                  'plant i to market j')

freight_cost = 90
cost = freight_cost * distances / 1000
c.setRecords(cost.reset_index())
c[i, j] = freight_cost*d[i, j] / 1000

print_records([d, c])

supply = gams.Equation(container=m,
                       name='supply',
                       domain=i,
                       description='Observe supply limit at plant i')

demand = gams.Equation(container=m,
                       name='demand',
                       domain=j,
                       description='Satisfy demand at market j')

supply[i] = gams.Sum(j, x[i, j]) <= a[i]
demand[j] = gams.Sum(i, x[i, j]) >= b[j]

obj = gams.Sum((i, j), c[i, j] * x[i, j])  # objective function

transport = gams.Model(container=m,
                       name='transport',
                       equations=[supply, demand],
                       problem='LP',
                       sense=gams.Sense.MIN,
                       objective=obj)  # problem

transport.solve(output=sys.stdout,
                options=gams.Options(equation_listing_limit=10,
                                     variable_listing_limit=10))

print(transport.getEquationListing())
print()
print(transport.getVariableListing())
print()
print(supply.getEquationListing())
print()
print(demand.getEquationListing())
print()
print(x.getVariableListing())
print()
print_records([x])
print('Optimum: ', transport.objective_value)

i :

         uni element_text
0    Seattle
1  San Diego

j :

        uni element_text
0  New York
1   Chicago
2    Topeka

a :

           i  value
0    Seattle  350.0
1  San Diego  600.0

b :

          j  value
0  New York  325.0
1   Chicago  300.0
2    Topeka  275.0

d :

        From        To  value
0    Seattle  New York    2.5
1    Seattle   Chicago    1.7
2    Seattle    Topeka    1.8
3  San Diego  New York    2.5
4  San Diego   Chicago    1.8
5  San Diego    Topeka    1.4

c :

           i         j  value
0    Seattle  New York  0.225
1    Seattle   Chicago  0.153
2    Seattle    Topeka  0.162
3  San Diego  New York  0.225
4  San Diego   Chicago  0.162
5  San Diego    Topeka  0.126

--- Job _SO5v4EldTZ_xZBIZMobBQg.gms Start 09/29/26 15:18:52 50.2.0 d60bb663 WEX-WEI x86 64bit/MS Windows
--- Applying:
    C:\Users\gajam\AppData\Local\Programs\Python\Python313\Lib\site-packages\gamspy_base\gmsprmNT.txt
--- GAMS Parameters defined
    LP cplex
    Input C:\Users\gajam\AppData\Local\Temp\tmpc2drioyt\_SO5v4EldTZ_xZBIZMobBQg.gms
    Output C:\Users\gajam\AppData\Local\Temp\tmpc2drioyt\_SO5v4EldTZ_xZBIZMobBQg.lst
    ScrDir C:\Users\gajam\AppData\Local\Temp\tmpc2drioyt\tmpmq85n538\
    SysDir C:\Users\gajam\AppData\Local\Programs\Python\Python313\Lib\site-packages\gamspy_base\
    LogOption 3
    Trace C:\Users\gajam\AppData\Local\Temp\tmpc2drioyt\_SO5v4EldTZ_xZBIZMobBQg.txt
    License C:\Users\gajam\Documents\GAMSPy\gamspy_license.txt
    OptFile 0
    OptDir C:\Users\gajam\AppData\Local\Temp\tmpc2drioyt\
    LimRow 10
    LimCol 10
    TraceOpt 3
    GDX C:\Users\gajam\AppData\Local\Temp\tmpc2drioyt\_SO5v4EldTZ_xZBIZMobBQgout.gdx
    SolPrint 0
    PreviousWork 1
    gdxSymbols newOrChanged
System information: 10 physical cores and 16 Gb physical memory detected
--- Starting compilation
--- _SO5v4EldTZ_xZBIZMobBQg.gms(71) 4 Mb
--- Starting execution: elapsed 0:00:00.018
--- Generating LP model transport
--- _SO5v4EldTZ_xZBIZMobBQg.gms(150) 4 Mb
---   6 rows  7 columns  19 non-zeroes
--- Range statistics (absolute non-zero finite values)
--- RHS       [min, max] : [ 2.750E+02, 6.000E+02] - Zero values observed as well
--- Bound     [min, max] : [        NA,        NA] - Zero values observed as well
--- Matrix    [min, max] : [ 1.260E-01, 1.000E+00]
--- Executing CPLEX (Solvelink=2): elapsed 0:00:00.036

IBM ILOG CPLEX   50.2.0 d60bb663 Jul 14, 2025          WEI x86 64bit/MS Window

*** This solver runs with a demo license. No commercial use.
--- GMO setup time: 0.00s
--- GMO memory 0.50 Mb (peak 0.50 Mb)
--- Dictionary memory 0.00 Mb
--- Cplex 22.1.2.0 link memory 0.00 Mb (peak 0.00 Mb)
--- Starting Cplex

Version identifier: 22.1.2.0 | 2024-11-25 | 0edbb82fd
CPXPARAM_Advance                                 0
CPXPARAM_Simplex_Display                         2
CPXPARAM_MIP_Display                             4
CPXPARAM_MIP_Pool_Capacity                       0
CPXPARAM_MIP_Tolerances_AbsMIPGap                0
Tried aggregator 1 time.
LP Presolve eliminated 0 rows and 1 columns.
Reduced LP has 5 rows, 6 columns, and 12 nonzeros.
Presolve time = 0.00 sec. (0.00 ticks)

Iteration      Dual Objective            In Variable           Out Variable
     1              73.125000  x(Seattle,'New York')demand('New York' slack
     2             119.025000     x(Seattle,Chicago)  demand(Chicago) slack
     3             153.675000  x('San Diego',Topeka)   demand(Topeka) slack
     4             153.675000x('San Diego','New York  supply(Seattle) slack

--- LP status (1): optimal.
--- Cplex Time: 0.00sec (det. 0.01 ticks)


Optimal solution found
Objective:          153.675000

--- Reading solution for model transport
--- Executing after solve: elapsed 0:00:00.174
--- _SO5v4EldTZ_xZBIZMobBQg.gms(209) 4 Mb
--- GDX File C:\Users\gajam\AppData\Local\Temp\tmpc2drioyt\_SO5v4EldTZ_xZBIZMobBQgout.gdx
*** Status: Normal completion
--- Job _SO5v4EldTZ_xZBIZMobBQg.gms Stop 09/29/26 15:18:52 elapsed 0:00:00.178
supply(Seattle)..  x(Seattle,New York) + x(Seattle,Chicago) + x(Seattle,Topeka) =L= 350 ; (LHS = 0)
supply(San Diego)..  x(San Diego,New York) + x(San Diego,Chicago) + x(San Diego,Topeka) =L= 600 ; (LHS = 0)
demand(New York)..  x(Seattle,New York) + x(San Diego,New York) =G= 325 ; (LHS = 0, INFES = 325 ****)
demand(Chicago)..  x(Seattle,Chicago) + x(San Diego,Chicago) =G= 300 ; (LHS = 0, INFES = 300 ****)
demand(Topeka)..  x(Seattle,Topeka) + x(San Diego,Topeka) =G= 275 ; (LHS = 0, INFES = 275 ****)
transport_objective..  0.225*x(Seattle,New York) + 0.153*x(Seattle,Chicago) + 0.162*x(Seattle,Topeka) + 0.225*x(San Diego,New York) + 0.162*x(San Diego,Chicago) + 0.126*x(San Diego,Topeka) - transport_objective_variable =E= 0 ; (LHS = 0)

x(Seattle,New York)
                (.LO, .L, .UP, .M = 0, 0, +INF, 0)
        1       supply(Seattle)
        1       demand(New York)
        0.225   transport_objective

x(Seattle,Chicago)
                (.LO, .L, .UP, .M = 0, 0, +INF, 0)
        1       supply(Seattle)
        1       demand(Chicago)
        0.153   transport_objective

x(Seattle,Topeka)
                (.LO, .L, .UP, .M = 0, 0, +INF, 0)
        1       supply(Seattle)
        1       demand(Topeka)
        0.162   transport_objective

x(San Diego,New York)
                (.LO, .L, .UP, .M = 0, 0, +INF, 0)
        1       supply(San Diego)
        1       demand(New York)
        0.225   transport_objective

x(San Diego,Chicago)
                (.LO, .L, .UP, .M = 0, 0, +INF, 0)
        1       supply(San Diego)
        1       demand(Chicago)
        0.162   transport_objective

x(San Diego,Topeka)
                (.LO, .L, .UP, .M = 0, 0, +INF, 0)
        1       supply(San Diego)
        1       demand(Topeka)
        0.126   transport_objective

transport_objective_variable
                (.LO, .L, .UP, .M = -INF, 0, +INF, 0)
       -1       transport_objective


supply(Seattle)..  x(Seattle,New York) + x(Seattle,Chicago) + x(Seattle,Topeka) =L= 350 ; (LHS = 0)
supply(San Diego)..  x(San Diego,New York) + x(San Diego,Chicago) + x(San Diego,Topeka) =L= 600 ; (LHS = 0)

demand(New York)..  x(Seattle,New York) + x(San Diego,New York) =G= 325 ; (LHS = 0, INFES = 325 ****)
demand(Chicago)..  x(Seattle,Chicago) + x(San Diego,Chicago) =G= 300 ; (LHS = 0, INFES = 300 ****)
demand(Topeka)..  x(Seattle,Topeka) + x(San Diego,Topeka) =G= 275 ; (LHS = 0, INFES = 275 ****)

x(Seattle,New York)
                (.LO, .L, .UP, .M = 0, 0, +INF, 0)
        1       supply(Seattle)
        1       demand(New York)
        0.225   transport_objective

x(Seattle,Chicago)
                (.LO, .L, .UP, .M = 0, 0, +INF, 0)
        1       supply(Seattle)
        1       demand(Chicago)
        0.153   transport_objective

x(Seattle,Topeka)
                (.LO, .L, .UP, .M = 0, 0, +INF, 0)
        1       supply(Seattle)
        1       demand(Topeka)
        0.162   transport_objective

x(San Diego,New York)
                (.LO, .L, .UP, .M = 0, 0, +INF, 0)
        1       supply(San Diego)
        1       demand(New York)
        0.225   transport_objective

x(San Diego,Chicago)
                (.LO, .L, .UP, .M = 0, 0, +INF, 0)
        1       supply(San Diego)
        1       demand(Chicago)
        0.162   transport_objective

x(San Diego,Topeka)
                (.LO, .L, .UP, .M = 0, 0, +INF, 0)
        1       supply(San Diego)
        1       demand(Topeka)
        0.126   transport_objective


x :

           i         j  level  marginal  lower  upper  scale
0    Seattle  New York   50.0     0.000    0.0    inf    1.0
1    Seattle   Chicago  300.0     0.000    0.0    inf    1.0
2    Seattle    Topeka    0.0     0.036    0.0    inf    1.0
3  San Diego  New York  275.0     0.000    0.0    inf    1.0
4  San Diego   Chicago    0.0     0.009    0.0    inf    1.0
5  San Diego    Topeka  275.0     0.000    0.0    inf    1.0

Optimum:  153.675